### ISSUE TITLE
Where to find source code?

### ISSUE THREAD

**Issue by downeymj** [hlnurse/rigpi#2]
Hi there! https://rigpi.net/downloads.html links to this repo for the source code but at the moment the only thing available is a license file and readme.

Where can we find the source code? Thanks in advance!

**Comment by ei8fdb** [comment]
I also have the same question. This looks a very interesting project. Congrats on it. :clap: The RigPi website says the software "will be available on GitHub as a free, open-source download. Add your own features to RSS!".

I'd like to try and possibly add features. Where can we find the source code? Thanks.

**Comment by ve3rx** [comment]
The license file and readme were posted in 2018. Nothing since. I would suspect some commercial vendor may have a finger in this, somehow.
If this was open source, it could have been posted sometime over the past 2 years, and updated as required.

**Comment by ei8fdb** [comment]
@downeymj I had a look on the RigPi forum and found some [message](https://groups.io/g/RigPi/topic/66451064#4128) [threads](https://groups.io/g/RigPi/topic/71045740#4915), including 2 comments from W6HN - Howard Nurse explaining [what software is closed/open source](https://groups.io/g/RigPi/message/4889) and [the plans to release the source code fully after version 2](https://groups.io/g/RigPi/message/4917) from W6HN - Howard Nurse.

**Comment by n3glv** [comment]
Contact MFJ

**Comment by n3glv** [comment]
Nearly every sub system / app is FOSS linux. It's not clear how much is
written by Howard, my bet is very little.
We have managed to install most of the apps, if you don't need the keyer
for the rig etc, there's not much that you can't do.

**Comment by TheRealNerdyDad** [comment]
RigPi 2 has been announced by MFJ.   Maybe getting source soon?

However, I believe N3GLV maybe correct in that the only thing W6HN has written is very little code, maybe the UI/UX for hamlib, but that's going to be about it.

Still wanting to see the source,
K5CBM

**Comment by northstarcomp** [comment]
They are claiming open source and yet no source code. They need to get on it or they could get in trouble as it is a violation of the License of OSS.

**Comment by downeymj** [comment]
Yeah, very disappointing. The RigPi website still says right up at the top that "the software is open source and can be easily modified" and "Software for RigPi will be available on GitHub as a free, open-source download" -- but there's still no OSI-licensed source code. Of course, you can buy v2 from MFJ, naturally. No problem in getting them the source code.

In the open source software industry, we call this type of thing "openwashing". I don't want to asumme bad intent, but I still repeat the question: Where is the promised open source-licensed code?

**Comment by TheRealNerdyDad** [comment]
Nurse said in their group.io group that most of the software was already open-sourced.   The only thing that isn't going to be open-sourced is the UI and its supporting software. ---- On Sun, 15 Nov 2020 17:19:51 -0600  notifications@github.com  wrote ----

Yeah, very disappointing. The RigPi website still says right up at the top that "the software is open source and can be easily modified" and "Software for RigPi will be available on GitHub as a free, open-source download" -- but there's still no OSI-licensed source code. Of course, you can buy v2 from MFJ, naturally. No problem in getting them the source code.

In the open source software industry, we call this type of thing "openwashing". I don't want to asumme bad intent, but I still repeat the question: Where is the promised open source-licensed code?

**Comment by n3glv** [comment]
WIr was also said in the unveiling video from Dyton some 2 years ago?
I went to github and found a project by this name and......
NOTHING
As far as I can tell the whole project was made out of foss code done by
others, fldigi, wsjtx etc. Only the front end skin was their work (MFJ)
The cw interface is from UK and available elsewhere etc.
W3YJ published his version of a remote rig setup with the uk board on qst.
What would be nice is an inventory or rasbian repo of all the apps used to
make rigpi.
Anyone tried to buy a rigpi w/o the cw etc options? dxengineering etc
refuses to sell the base system, only the $300 one...
CLEARLY this project was a prime example of OPENWASHING!

**Comment by wp4nuv** [comment]
I don't have the RigPi, but the [HamPi](https://sourceforge.net/projects/hampi/files/2020-09%20Release/) image has everything you need for Amateur Radio.

**Comment by aaron1959** [comment]
Rigpi is now being redistributed for free on various drop box accounts as well as some file sharing sites. this is a very recent development.

**Comment by downeymj** [comment]
> Rigpi is now being redistributed for free on various drop box accounts as well as some file sharing sites. this is a very recent development.

That's good news. At least some

Can someone just put the stuff from Dropbox on GitHub or some other git repo? 

Given the several years of evasion by the maintainer here it's pretty clear despite years of offers to help, they have zero intention of following the legal requirements of GPL license on the software they used, and make the source code available.
