### ISSUE TITLE
2021 = 3 years of nothingness

### ISSUE THREAD

**Issue by FrostNetworks** [hlnurse/rigpi#4]
WTF is wrong with this picture, imagine this in an advert; "commercially sold open source software"... just ponder on that for a while...

Quote from RigPi homepage; "Software for RigPi will be available on GitHub as a free, open-source download. Add your own features to RSS!"

So, still boosting on the M*J site about being "open source" and "free" blah blah blah, are we? BS!

And all links on the net bragging about the same thing, open this, source that, free nada...!
Simple truth ? MFJ would not give away a dust-rat from the floor for free, let alone a piece of "open source" software.
Not as long as they still can make a single cent from it, and would rather torch and burn their entire stock before giving a
single piece of anything away free. 

Yes folks, that´s the sad truth. And waiting here on GitHub are us morons who still hope the will obey the promises made 
GitHub, the original creator of the software (before greedy MFJ got their fingers on it) and all others who knows what "open source" means.
Maybe the good folks at MFJ are poor at English ? 
Maybe Git Hub should kick them out for obviously NOT sharing anything?
Kick them out for charging customers for "free open source" software ?
For using "open source" as a major salespoint and using the name "Git Hub" in their promo as well, when in fact NOTHING is shared here or elsewhere?

Well, perhaps MFJ is a well paying customer, which I am not, so let them keep their empty account, don´t rock the boat?

Seriously Git Hub, you have many eyes on you. You´ve done this before. 
Kick them the heck out, since they still (AFTER 3 YEARS!) share nothing and breach their contract of intent and the whole idea of open source I might add.

@ all of Ham community, write about this idiocracy, talk about "MFJ open source RigPi", spread the word around the world. 
This is a total disgrace and a "spit in the face" (again) on the idea of open source in general, and on all of the thousands "follow the leader - don´t speak too loud - we´ll behave oh Lord of the Antennaswitch master, sire" -ham's in general.
But enough is enough.

MFJ is ripping you off making you have to pay dearly for what they call "free" (duh?) "open source" software
(yeah, the OS they use AND MAKE YOUR PAY FOR on ready-made SD-cards is both free and open) and this is just bleedin´ scandalous. Outrageous. In Swedish; "helt åt helvete" (Google will translate that one for you).

I have no illusions regarding MFJ to anytime before the second coming of Christ suddenly changing their minds 
or me by this text at GitHub making any difference in any way, shape or form.
But I am a bit curious, will Git Hub act upon MFJ or me and my little post here?
Let´s see how long this post will be up before someone with money makes it disappear...

Btw, there are many, many other FREE and true open source solutions here on Git Hub and elsewhere on the web that does the same thing. It just ticks me off when big corporations p-in-your-face-people promise gold and prove to be lying to a whole community and, frankly my dear, just does´nt give a damn about it! (oh btw, that´s the same community that for some incomprehensible reason still keeps them in business none the less).

This is a scandal and intentional damage upon all that open source stands for and was ever meant to be, and perhaps yet another signal of it´s demise.

73s and greetings from Sweden!

**Comment by mbridak** [comment]
Well the license.php file in the rigpi html folder says it's free software
covered under the gpl v3 and can be freely distributed.
So you yourself should be able to copy the contents of the folder minus the
3rd party libraries to a repo of your own making.
You wouldn't need to wait for Howard or MFJ to do it. It's all plaintext
php and js files.

Just sayin.

**Comment by hlnurse** [comment]
MFJ is not involved in the decision to provide RigPi here on GitHub and has given their blessing to do so.  My lack of progress has nothing to do with MFJ.  The main reason for not proceeding is because of time constraints.  I have asked others for help to manage RigPi on GitHub without success.

RigPi is open source except for several json elements created under license with a commercial product.

--Howard

**Comment by chazrich** [comment]
Howard, what kind of help do you need? I am willing to help if I can. 

--Charles
AK4SR

**Comment by hlnurse** [comment]
Thanks, Charles!  I’ll be in touch via private email to discuss more.

—Howard

**Comment by downeymj** [comment]
>I’ll be in touch via private email to discuss more.

Why not just say right here what you need in order to publish the source code, which you are legally required to do since you have distributed changes and modifications to other software licensed under GPL?

Here's the GitHub help page on how to upload files. It takes a few minutes, not a few years: https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository

We're waiting.
